
import React, { useEffect, useState } from 'react';
import {
  View,
  StyleSheet,
  Keyboard,
 } from 'react-native';
import imageIndex from '@assets/imageIndex';
import { Color } from '@theme/color';
 import ScreenNameEnum from '@routes/screenName.enum';
import { useNavigation } from '@react-navigation/native';
 import CreateGroupName from '@components/modal/GroupMemberModal/CreateGroupName';
import SelectFriendCom from '@components/common/SelectFriendCom/SelectFriendCom';
import { useSelector } from 'react-redux';
import { RootState } from '@redux/store';
import { createGroup, getGroupActivities, getGroupMembers } from '@redux/Api/GroupApi';
import { SafeAreaView } from 'react-native-safe-area-context';
import useSignup from '@screens/Auth/signup/useSignup';
import { CustomStatusBar, HeaderCustom, SuccessMessageCustom } from '@components/index';
import { t } from 'i18next';
const CreateGroupScreen = () => {
  const { setToestMess, toestMess } = useSignup();
  const token = useSelector((state: RootState) => state.auth.token);
  const navigation = useNavigation();
  const [loder, setloder] = useState(false);
  const [groupNameState, setGroupNameState] = useState('');
  const [selectedMembers, setSelectedMembers] = useState<Member[]>([]);
  const [isAutoGenerated, setIsAutoGenerated] = useState(true); // Track auto-name
  const [isKeyboardVisible, setKeyboardVisible] = useState(false);
  const [isSearchFocused, setSearchFocused] = useState(false);
  const [toastMessage, setToastMessage] = useState('');
  const [toestMessColorGreen, setToestMessColorGreen] = useState(true);
  const [groupsData, setGroupsData] = useState([]);
  const [loadingGroups, setLoadingGroups] = useState(true); // optional
  const [group_Id, setGroup_Id] = useState(null); // optional
  const [group_api_create, setGroup_api_create] = useState(false); // optional

  const showToast = (message: string, isSuccess: boolean = true) => {
    setToastMessage(message);
    setToestMessColorGreen(isSuccess);
    setToestMess(true);
    setTimeout(() => {
      setToestMess(false);
    }, 2000);
  };

  useEffect(() => {
    const showSub = Keyboard.addListener('keyboardDidShow', () => setKeyboardVisible(true));
    const hideSub = Keyboard.addListener('keyboardDidHide', () => setKeyboardVisible(false));
    return () => {
      showSub.remove();
      hideSub.remove();
    };
  }, []);

  const handleCreateGroup = async () => {
     if (!selectedMembers || selectedMembers.length === 0) {
      showToast("Please select at least one friend.", false);
      return;
    }
    const getMemberName = (member) =>
  (member?.name || member?.username || member?.id).trim();

const finalGroupName = groupNameState?.trim()
  ? groupNameState.trim()
  : selectedMembers.length === 1
    ? getMemberName(selectedMembers[0])
    : selectedMembers.length === 2
      ? `${getMemberName(selectedMembers[0])} & ${getMemberName(selectedMembers[1])}`
      : selectedMembers.length > 2
        ? `${selectedMembers
            .slice(0, -1)
            .map(getMemberName)
            .join(', ')} & ${getMemberName(selectedMembers[selectedMembers.length - 1])}`
        : '';
 

const createGroupName = (groupNameState: string, selectedMembers: string | object[]) => {
  // If user manually entered a group name, use that
  if (groupNameState?.trim()) {
    return groupNameState.trim();
  }
 
  const names = selectedMembers?.map(getMemberName).filter(Boolean);
 
  if (names.length === 0) return '';
 
  if (names.length === 1) {
    return names[0];
  }
 
  if (names.length === 2) {
    return `${names[0]} & ${names[1]}`;
  }
 
  // 3 or more members
  return `${names.slice(0, -1).join(', ')} & ${names[names?.length - 1]}`;
};

setloder(true)
     try {
      const finalGroupName = createGroupName(groupNameState, selectedMembers);
      // ✅ Safe array mapping with guards
     const memberUsernames = Array.isArray(selectedMembers) 
       ? selectedMembers.map(member => member?.username ||  member?.name ||member?.id).filter(Boolean)
       : []; // ✅ FIXED
      // const memberUsernames = selectedMembers.map(member => member.id);
        const response = await createGroup(token, finalGroupName, memberUsernames);
      const createdGroupId = response?.data?.messaged?.split(' ')[0]?.trim();
      setGroup_Id(createdGroupId);
      setGroup_api_create(true);
          setloder(false)
      showToast("Group created successfully!", true);
setTimeout(() => {
  navigation.goBack();
}, 300);  
    } catch (error: string | object ) {
                setloder(false)

 
      if (error.response && error.response.status === 409) {
                  setloder(false)

        const errorMsg  = error.response.data.error;
        const existingGroupName   = error.response.data.existing_group_name;
          showToast(`${errorMsg} Group name: ${existingGroupName}`, false);
      } else {
                  setloder(false)

            showToast("Group creation failed. Please try again.", false);
      }
    }
  }


  useEffect(() => {
    const fetchGroupDetails = async () => {
      if (!group_api_create || !group_Id) return;

      try {
        setLoadingGroups(true);

        const groupName = groupNameState;
         const groupId = group_Id;
         // ✅ Fetch activities
        let activities = {
          current_page: 1,
          results: [],
          total_pages: 1,
        };
        try {
          const activityData = await getGroupActivities(token, groupId);
          activities = {
            current_page: activityData?.current_page || 2,
            results: activityData?.results || [],
            total_pages: activityData?.total_pages,
          };
        } catch (err) {
         }

        // ✅ Fetch members
        let members = [];
        try {
          const memberData = await getGroupMembers(token, groupId);
          members = memberData?.results || [];
        } catch (err) {
         }
        const finalGroup = {
          groupId,
          groupName,
          isMuted: false,
          members,
          activities,
        };

        setGroupsData([finalGroup]);
 
        //  Navigate after slight delay (optional)
        setTimeout(() => {
           // navigation.navigate('WatchWithFrind', {
          navigation.navigate('WatchWithFrind', {
            // group: finalGroup,
            groupProps: finalGroup,
            groupId: groupId,
            // type: 'createGroup',
          });
        }, 1000);
      } catch (err) {
       } finally {
        setLoadingGroups(false);
      }
    };

    fetchGroupDetails();
  }, [group_api_create, group_Id]);




  // {group_api_create && (
  //   fetchGroups()
  // ) }
  // useEffect(() => {
  //   if (group_api_create && groupsData.length > 0 && group_Id) {
   //     navigation.navigate('WatchWithFrind', {
  //       group: groupsData,
  //       groupId: group_Id,
  //       type: "createGroup", // Optional
  //     });
  //   }
  // }, [group_api_create, groupsData, group_Id]);

  // setTimeout(() => {
  //     navigation.navigate('WatchWithFrind', {

  //       group: groupsData,
  //       groupId: group_Id, // 👈 now groupId is also explicitly passed

  //       type: "createGroup"
  //     });
  //   }, 1000);

   const renderContent = () => (
    <View style={{ justifyContent: 'space-between', flex: 1, }}>

      <SelectFriendCom
        setSearchFocused={setSearchFocused}
        onSelectionChange={setSelectedMembers}
        token={token}
        type="createGroup"
      />
      {!(isSearchFocused && isKeyboardVisible) && (
        <CreateGroupName
          groupName={groupNameState}
          setGroupName={setGroupNameState}
          onClose={() => navigation.goBack()}
          onCreate={handleCreateGroup}
          showToast={showToast}
          toestMess={toestMess}
          selectedMembers={selectedMembers}
          setIsAutoGenerated={setIsAutoGenerated}
         />
      )}
    </View>
  );
  return (
    <SafeAreaView style={styles.container}>
      <CustomStatusBar />
      <View style={{ paddingTop: 18, }} >
        <HeaderCustom
        // 
          title={(t("discover.addfriend"))}
          backIcon={imageIndex.backArrow}
          rightIcon={false}
          onRightPress={() => navigation.navigate(ScreenNameEnum.OtherTaingPrfofile)}
        />
      </View>
      {renderContent()}
      {toestMess && (
        <SuccessMessageCustom
          textColor={Color.whiteText}
          color={toestMessColorGreen ? Color.green : Color.red}
          message={toastMessage}
        />
      )}

    </SafeAreaView>
  );
};
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Color.background,
  },

});

export default React.memo(CreateGroupScreen);
