require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]}
    )',
    __dir__
  ]
).strip

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Handle use_frameworks
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'reelrecs' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => false   

  )

  # react-native-permissions path
  # permissions_path = '../node_modules/react-native-permissions/ios'

  # Example permissions (uncomment when needed)
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
