export default {
  welcome: require('./images/welcome.png'),
  appLogo: require('./images/appLogo.png'),
  eyes: require('./images/eyes.png'),
  fb: require('./images/fb.png'),
  apple: require('./images/apple.png'),
  google: require('./images/google.png'),
  home: require('./images/home.png'),
  homeActive: require('./images/homeActive.png'),
  reelRecsHome: require('./images/reelRecsHome.png'),
  UserProfile: require('./images/UserProfile.png'),
  discover: require('./images/discover.png'),
  discoverActive: require('./images/discoverActive.png'),
  ranking: require('./images/mdRankings.png'),
  rankingActive: require('./images/rankingActive.png'),
  usersGroup: require('./images/usersGroup.png'),
  usersGroupActive: require('./images/usersGroupActive.png'),
  profileActive: require('./images/profileActive.png'),
  notification: require('./images/notification.png'),
  search: require('./images/search.png'),
  ratingLabel: require('./images/ratingLabel.png'),
  rightArrow: require('./images/rightArrow.png'),
  mdRankings: require('./images/mdRankings.png'),
  saveMark: require('./images/saveMark.png'),
  close: require('./images/close.png'),
  moviesPoster: require('./images/moviesPoster.png'),
  redClose: require('./images/redClose.png'),
  play: require('./images/play.png'),
  stopPlay: require('./images/stopPlay.png'),
  acrtivePlay: require('./images/acrtivePlay.png'),
  orCircle: require('./images/orCircle.png'),
  bluePlay: require('./images/bluePlay.png'),
  stepPogremBar: require('./images/stepPogremBar.png'),
  stepCom: require('./images/stepCom.png'),
  chevronUp: require('./images/chevronUp.png'),
  downDown: require('./images/downDown.png'),
  backArrow: require('./images/backArrow.png'),
  closeWhite: require('./images/closeWhite.png'),
  mx: require('./images/mx.png'),
  menu: require('./images/menu.png'),
  profielImg: require('./images/profielImg.png'),
  save: require('./images/save.png'),
  WatchNowButton: require('./images/WatchNowButton.png'),
  checkBox: require('./images/checkBox.png'),
  checKBoxActive: require('./images/checKBoxActive.png'),
  amazon: require('./images/amazon.png'),
  closeimg: require('./images/closeimg.png'),
  chevronDown: require('./images/chevronDown.png'),
  mess: require('./images/mess.png'),
  Addplus: require('./images/Addplus.png'),
  Info: require('./images/Info.png'),
  heart: require('./images/heart.png'),
  view: require('./images/view.png'),
  pause: require('./images/pause.png'),
  second: require('./images/second.png'),
  ten10: require('./images/ten10.png'),
  polygon: require('./images/polygon.png'),
  send: require('./images/send.png'),
  settings: require('./images/settings.png'),
  edit: require('./images/edit.png'),
  gallery: require('./images/gallery.png'),
  camera: require('./images/camera.png'),
  bgWatch: require('../assets/images/bgWatch.png'),
  reelRecs: require('../assets/images/reelRecs.png'),
  mutedIcon: require('../assets/images/mutedIcon.png'),
  puased: require('../assets/images/puased.png'),
  mute: require('../assets/images/mute.png'),
  progressBarCenter: require('../assets/images/progressBarCenter.png'),
  Welcomeupdate: require('../assets/images/Welcomeupdate.png'),
  settingUser: require('../assets/images/settingUser.png'),
  settingPlay: require('../assets/images/settingPlay.png'),
  settingPrivacy: require('../assets/images/settingPrivacy.png'),
  settingHelp: require('../assets/images/settingHelp.png'),
  settingExit: require('../assets/images/settingExit.png'),
  sortBy: require('../assets/images/sortBy.png'),
  invitIcon: require('../assets/images/invitIcon.png'),
  thumpUP: require('../assets/images/thumpUP.png'),
  thumpDown: require('../assets/images/thumpDown.png'),
  filterImg: require('../assets/images/filterImg.png'),
  arrowUp: require('../assets/images/arrowUp.png'),
  arrowDown: require('../assets/images/arrowDown.png'),
  like: require('../assets/images/like.png'),
  disLike: require('../assets/images/disLike.png'),
  Check: require('../assets/images/Check.png'),
  UserAdd: require('../assets/images/UserAdd.png'),
  bellNotification: require('../assets/images/bellNotification.png'),
  delete: require('../assets/images/delete.png'),
  doubleCheck: require('../assets/images/doubleCheck.png'),
  editSpace: require('../assets/images/editSpace.png'),
  modalitWasPoster: require('../assets/images/modalitWasPoster.png'),
  redCloseActive: require('../assets/images/redCloseActive.png'),
  featureRequest: require('../assets/images/featureRequest.png'),
  playCircle: require('../assets/images/playCircle.png'),
  settingHelpImg: require('../assets/images/settingHelpImg.png'),
  commnet: require('../assets/images/commnet.png'),
  sendComment: require('../assets/images/sendComment.png'),
  questionMark: require('../assets/images/questionMark.png'),
  volumeOff: require('../assets/images/volumeOff.png'),
  normalNotification: require('../assets/images/normalNotification.png'),
  rankingTab: require('../assets/images/rankingTab.png'),
  closeCircle: require('../assets/images/closeCircle.png'),
  Introduction: require('../assets/images/Introduction.png'),
  step1: require('../assets/images/step1.png'),
  step3: require('../assets/images/step3.png'),
  WatchNowButton2: require('../assets/images/WatchNowButton2.png'),
  step4: require('../assets/images/step4.png'),
  SingleMovi: require('../assets/images/SingleMovi.png'),
  SingleMovie7: require('../assets/images/SingleMovie7.png'),
  SingleMovieSlide2: require('../assets/images/SingleMovieSlide2.png'),
  SingleMovie6: require('../assets/images/SingleMovie6.png'),
  SingleMovie3: require('../assets/images/SingleMovie3.png'),
  SingleMovie4: require('../assets/images/SingleMovie4.png'),
  SingleMovie8: require('../assets/images/SingleMovie8.png'),
  SingleMovie9: require('../assets/images/SingleMovie9.png'),
  LargePortraitPoster: require('../assets/images/LargePortraitPoster.png'),
  LargePortraitPoster1: require('../assets/images/LargePortraitPoster1.png'),
  LargePortraitPoster2: require('../assets/images/LargePortraitPoster2.png'),
  SingleMovieSlide3: require('../assets/images/SingleMovieSlide3.png'),
  SingleMovie5: require('../assets/images/SingleMovie5.png'),
  // closeCircle: require('../assets/images/closeCircle.png'),


















  welcomePost1: require('../assets/welcomePost/welcomePost1.png'),
  welcomePost2: require('../assets/welcomePost/welcomePost2.png'),
  welcomePost3: require('../assets/welcomePost/welcomePost3.png'),
  welcomePost4: require('../assets/welcomePost/welcomePost4.png'),
  welcomePost5: require('../assets/welcomePost/welcomePost5.png'),
  welcomePost6: require('../assets/welcomePost/welcomePost1.png'),
  welcomePost7: require('../assets/welcomePost/welcomePost7.png'),
  welcomePost8: require('../assets/welcomePost/welcomePost8.png'),
  welcomePost9: require('../assets/welcomePost/welcomePost9.png'),
  welcomePost10: require('../assets/welcomePost/welcomePost10.png'),
  welcomePost11: require('../assets/welcomePost/welcomePost11.png'),
  welcomePost12: require('../assets/welcomePost/welcomePost12.png'),
  welcomePost13: require('../assets/welcomePost/welcomePost13.png'),
  welcomePost14: require('../assets/welcomePost/welcomePost14.png'),
  welcomePost15: require('../assets/welcomePost/welcomePost15.png'),
  welcomePost16: require('../assets/welcomePost/welcomePost16.png'),
  welcomePost17: require('../assets/welcomePost/welcomePost17.png'),
  welcomePost18: require('../assets/welcomePost/welcomePost18.png'),
  welcomePost19: require('../assets/welcomePost/welcomePost19.png'),
  welcomePost20: require('../assets/welcomePost/welcomePost20.png'),
  welcomePost21: require('../assets/welcomePost/welcomePost21.png'),
  welcomePost22: require('../assets/welcomePost/welcomePost22.png'),
  welcomePost23: require('../assets/welcomePost/welcomePost23.png'),
  // welcomePost24: require('../assets/welcomePost/welcomePost24.png'),

}; 